const AIRLINES: Record<string, string> = {
  AA: "American Airlines", AC: "Air Canada", AF: "Air France",
  AI: "Air India", AK: "AirAsia", AM: "Aeromexico",
  AR: "Aerolíneas Argentinas", AT: "Royal Air Maroc", AV: "Avianca",
  AY: "Finnair", AZ: "ITA Airways", BA: "British Airways",
  BG: "Biman Bangladesh", BI: "Royal Brunei Airlines", BR: "EVA Air",
  BW: "Caribbean Airlines", CA: "Air China", CI: "China Airlines",
  CX: "Cathay Pacific", CZ: "China Southern Airlines",
  DL: "Delta Air Lines", EK: "Emirates", ET: "Ethiopian Airlines",
  EY: "Etihad Airways", FJ: "Fiji Airways", FZ: "flydubai",
  GA: "Garuda Indonesia", GF: "Gulf Air", HA: "Hawaiian Airlines",
  HM: "Air Seychelles", HR: "Hahn Air", IB: "Iberia",
  IC: "IndiGo", IK: "Imair Airlines", IR: "Iran Air",
  JL: "Japan Airlines", JP: "Adria Airways", JQ: "Jetstar",
  JU: "Air Serbia", KE: "Korean Air", KL: "KLM",
  KM: "Air Malta", KQ: "Kenya Airways", KU: "Kuwait Airways",
  LA: "LATAM Airlines", LH: "Lufthansa", LO: "LOT Polish Airlines",
  LX: "Swiss International Air Lines", LY: "El Al",
  MH: "Malaysia Airlines", MK: "Air Mauritius", MS: "EgyptAir",
  MU: "China Eastern Airlines", MX: "Breeze Airways",
  NH: "All Nippon Airways", NZ: "Air New Zealand",
  OK: "Czech Airlines", OS: "Austrian Airlines",
  OZ: "Asiana Airlines", PC: "Pegasus Airlines",
  PK: "Pakistan International Airlines", PR: "Philippine Airlines",
  PS: "Ukraine International Airlines", PX: "Air Niugini",
  PY: "Surinam Airways", QF: "Qantas", QR: "Qatar Airways",
  RJ: "Royal Jordanian", RO: "TAROM",
  S7: "S7 Airlines", SA: "South African Airways",
  SG: "SpiceJet", SK: "Scandinavian Airlines",
  SN: "Brussels Airlines", SQ: "Singapore Airlines",
  SU: "Aeroflot", SV: "Saudi Arabian Airlines",
  TG: "Thai Airways", TK: "Turkish Airlines",
  TP: "TAP Air Portugal", TW: "T'way Air",
  UA: "United Airlines", UB: "Myanmar National Airlines",
  UK: "Vistara", UL: "SriLankan Airlines",
  UN: "Transaero", US: "US Airways",
  UX: "Air Europa", VN: "Vietnam Airlines",
  VT: "Air Tahiti", VW: "Transportes Aeromar",
  W6: "Wizz Air", WN: "Southwest Airlines",
  WS: "WestJet", XY: "Flynas", ZH: "Shenzhen Airlines",
};

export function getAirlineName(code: string): string {
  return AIRLINES[code.toUpperCase()] ?? code;
}
